import type { Metadata } from "next"
import "./globals.css"
import Navabar from "@/components/Navbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="bg-light-primary text-dark-primary font-poppins">
        <Navabar />
        {children}
      </body>
    </html>
  )
}
